# Generated by Django 3.2.4 on 2021-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=80, verbose_name='Заголовок1')),
                ('about_content1', models.TextField(verbose_name='Контент')),
                ('title2', models.CharField(max_length=80, verbose_name='Заголовок2')),
                ('about_content2', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('email', models.CharField(max_length=30, verbose_name='Почта')),
                ('telefon', models.CharField(max_length=30, verbose_name='Телефон')),
                ('second_telefon', models.CharField(max_length=30, verbose_name='Второй телефон')),
            ],
            options={
                'verbose_name': 'Kontakts',
                'verbose_name_plural': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('slider_content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Slider Info',
                'verbose_name_plural': 'Slider Info',
            },
        ),
    ]
